import { ArrowDownUp, Ban, CheckCircle2, ChevronRight, RefreshCw, Sparkles } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { confirmCluster, getClusters, getSchemaFields, getSuggestions, ignoreCluster, reevaluate, type Cluster, type ConfirmRequest, type ConfirmResult, type IgnoreRequest } from '../../api/client';
import { EmptyState, ErrorState, LoadingState } from '../../components/StateViews';
import { useAsync } from '../../hooks/useAsync';

export function TrainingPage({ scanId }: { scanId: string }) {
  const state = useAsync(() => getClusters(scanId), [scanId]);
  const clusters = useMemo(() => [...(state.data ?? [])].sort((a, b) => b.device_count - a.device_count), [state.data]);
  const [selected, setSelected] = useState<Cluster | null>(null);
  const [reevaluating, setReevaluating] = useState(false);
  const [actionMessage, setActionMessage] = useState<string | null>(null);
  useEffect(() => { if (!selected && clusters.length) setSelected(clusters[0]); }, [clusters, selected]);

  async function runAgain() {
    setReevaluating(true); setActionMessage(null);
    try { await reevaluate(scanId); setActionMessage('Re-evaluation queued. Open Scan activity to follow device results.'); }
    catch (reason) { setActionMessage(reason instanceof Error ? reason.message : 'Could not queue re-evaluation.'); }
    finally { setReevaluating(false); }
  }

  if (state.loading) return <section className="page"><LoadingState label="Loading unmatched command clusters" /></section>;
  if (state.error) return <section className="page"><ErrorState message={state.error} retry={state.reload} /></section>;
  if (!clusters.length) return <section className="page"><header className="page-header"><div><span className="eyebrow">Mapping trainer</span><h1>Human-reviewed learning queue</h1><p>No open clusters remain for this scan.</p></div><button className="button secondary" disabled={reevaluating} onClick={runAgain}><RefreshCw size={15} />{reevaluating ? 'Queuing…' : 'Re-evaluate scan'}</button></header>{actionMessage && <p className="action-message" role="status">{actionMessage}</p>}<EmptyState title="Nothing needs labelling" detail="Every observed line matched a known vendor-pack mapping, or all clusters have been confirmed." /></section>;

  return <section className="page"><header className="page-header"><div><span className="eyebrow">Mapping trainer</span><h1>Resolve unknown commands</h1><p>Suggestions only pre-fill the review. The exact learned-pack fragment is generated by the backend and requires human confirmation.</p></div><div className="header-actions"><div className="security-pill"><ArrowDownUp size={15} />Largest impact first</div><button className="button secondary" disabled={reevaluating} onClick={runAgain}><RefreshCw size={15} />{reevaluating ? 'Queuing…' : 'Re-evaluate'}</button></div></header>{actionMessage && <p className="action-message" role="status">{actionMessage}</p>}
    <div className="training-layout"><aside className="cluster-list panel"><div className="panel-heading"><div><span className="panel-label">Open clusters</span><h2>{clusters.length} questions</h2></div></div>{clusters.map((cluster) => <button key={cluster.cluster_id} className={`cluster-row ${selected?.cluster_id === cluster.cluster_id ? 'active' : ''}`} onClick={() => setSelected(cluster)}><div><code>{cluster.signature}</code><small>{cluster.vendor}{cluster.scope ? ` · ${cluster.scope}` : ''}</small></div><span className="impact-count"><strong>{cluster.device_count}</strong> devices</span><ChevronRight size={15} /></button>)}</aside>{selected && <ClusterReview key={selected.cluster_id} cluster={selected} onConfirmed={() => { setSelected(null); state.reload(); }} />}</div>
  </section>;
}

function ClusterReview({ cluster, onConfirmed }: { cluster: Cluster; onConfirmed: () => void }) {
  const suggestionsState = useAsync(() => getSuggestions(cluster.cluster_id), [cluster.cluster_id]);
  const fieldsState = useAsync(getSchemaFields, []);
  const [field, setField] = useState<string | null>(null);
  const [absent, setAbsent] = useState<'unknown' | 'default'>('unknown');
  const [defaultValue, setDefaultValue] = useState('');
  const [defaultOsVersion, setDefaultOsVersion] = useState('');
  const [matchedValue, setMatchedValue] = useState('');
  const [author, setAuthor] = useState('');
  const [saving, setSaving] = useState<'mapping-preview' | 'mapping-confirm' | 'ignore-preview' | 'ignore-confirm' | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [mappingPreview, setMappingPreview] = useState<ConfirmResult | null>(null);
  const [ignoreOpen, setIgnoreOpen] = useState(false);
  const [ignoreReason, setIgnoreReason] = useState('');
  const [ignorePreview, setIgnorePreview] = useState<ConfirmResult | null>(null);

  if ((suggestionsState.loading && !suggestionsState.data) || (fieldsState.loading && !fieldsState.data)) return <div className="review-pane"><LoadingState label="Ranking canonical fields" /></div>;
  if (suggestionsState.error) return <div className="review-pane"><ErrorState message={suggestionsState.error} retry={suggestionsState.reload} /></div>;
  if (fieldsState.error) return <div className="review-pane"><ErrorState message={fieldsState.error} retry={fieldsState.reload} /></div>;

  const candidates = suggestionsState.data?.candidates ?? [];
  const selectedField = field ?? candidates[0]?.canonical_field ?? '';
  const selectedSchemaField = fieldsState.data?.find((item) => item.path === selectedField);
  const defaultNeedsValue = absent === 'default' && selectedSchemaField?.collection !== true;
  const matchedValueRequired = selectedSchemaField?.type === 'boolean';
  const mappingIncomplete = !selectedField || (defaultNeedsValue && (!defaultValue || !defaultOsVersion.trim())) || (matchedValueRequired && matchedValue === '');
  const payload = (): ConfirmRequest => ({
    canonical_field: selectedField,
    absent,
    ...(defaultNeedsValue ? { default: parseValue(defaultValue), default_os_version: defaultOsVersion.trim() } : {}),
    ...(matchedValue !== '' ? { value: parseValue(matchedValue) } : {}),
    ...(author.trim() ? { author: author.trim() } : {}),
  });

  async function requestPreview() {
    if (!selectedField) { setError('Choose a canonical field before requesting a preview.'); return; }
    if (defaultNeedsValue && !defaultValue) { setError('State the verified default value.'); return; }
    if (defaultNeedsValue && !defaultOsVersion.trim()) { setError('State which OS versions this default applies to.'); return; }
    if (matchedValueRequired && matchedValue === '') { setError('State the true or false value this command represents.'); return; }
    setSaving('mapping-preview'); setError(null);
    try { setMappingPreview(await confirmCluster(cluster.cluster_id, payload(), true)); }
    catch (reason) { setError(reason instanceof Error ? reason.message : 'Preview failed.'); }
    finally { setSaving(null); }
  }

  async function confirm() {
    if (!selectedField || !mappingPreview) { setError('Preview the exact pack fragment before confirming it.'); return; }
    setSaving('mapping-confirm'); setError(null);
    try { await confirmCluster(cluster.cluster_id, payload()); onConfirmed(); }
    catch (reason) { setError(reason instanceof Error ? reason.message : 'Confirmation failed.'); }
    finally { setSaving(null); }
  }

  const ignorePayload = (): IgnoreRequest => ({
    reason: ignoreReason,
    ...(author.trim() ? { author: author.trim() } : {}),
  });

  async function requestIgnorePreview() {
    if (ignoreReason.trim().length < 2) { setError('Explain why this line is not a security setting.'); return; }
    setSaving('ignore-preview'); setError(null);
    try { setIgnorePreview(await ignoreCluster(cluster.cluster_id, ignorePayload(), true)); }
    catch (reason) { setError(reason instanceof Error ? reason.message : 'Preview failed.'); }
    finally { setSaving(null); }
  }

  async function confirmIgnore() {
    if (!ignorePreview) { setError('Preview the exact ignore entry before confirming it.'); return; }
    setSaving('ignore-confirm'); setError(null);
    try { await ignoreCluster(cluster.cluster_id, ignorePayload()); onConfirmed(); }
    catch (reason) { setError(reason instanceof Error ? reason.message : 'Ignore failed.'); }
    finally { setSaving(null); }
  }

  return <div className="review-pane panel"><div className="review-header"><span className="panel-label">Normalised command</span><code>{cluster.signature}</code><p className="sample-line"><span>Redacted sample</span><code>{cluster.sample_line}</code></p><div className="impact-summary"><strong>{cluster.device_count}</strong> devices · <strong>{cluster.occurrence_count}</strong> matching lines covered by this answer</div></div><fieldset><legend>Choose one canonical field</legend><div className="suggestion-list">{candidates.map((item) => <label key={item.canonical_field} className={`suggestion ${selectedField === item.canonical_field ? 'selected' : ''}`}><input type="radio" name="field" value={item.canonical_field} checked={selectedField === item.canonical_field} onChange={() => { setField(item.canonical_field); setMappingPreview(null); }} /><span className="score">{Math.round(item.score * 100)}</span><div><code>{item.canonical_field}</code><p>{item.description}</p><small>{item.tier} suggestion</small></div></label>)}<label className={`suggestion none ${selectedField === '' ? 'selected' : ''}`}><input type="radio" name="field" checked={selectedField === ''} onChange={() => { setField(''); setMappingPreview(null); }} /><span className="score">—</span><div><strong>None of these</strong><p>Leave this cluster unresolved. It will continue to produce NOT DETERMINED.</p></div></label></div><label className="field"><span>Canonical field — select any schema path</span><input list={`fields-${cluster.cluster_id}`} value={selectedField} onChange={(event) => { setField(event.target.value); setMappingPreview(null); }} placeholder="Search or enter a canonical field" /></label><datalist id={`fields-${cluster.cluster_id}`}>{fieldsState.data?.map((item) => <option key={item.path} value={item.path}>{item.description}</option>)}</datalist></fieldset>
    {selectedField && <fieldset><legend>Mapping semantics</legend><div className="radio-row"><label><input type="radio" checked={absent === 'unknown'} onChange={() => { setAbsent('unknown'); setMappingPreview(null); }} />Unknown — do not infer a device default</label><label><input type="radio" checked={absent === 'default'} onChange={() => { setAbsent('default'); setMappingPreview(null); }} />Use a verified device default</label></div>{absent === 'default' && selectedSchemaField?.collection === true && <p className="field-guidance">For a collection, no matching line means an empty list; no scalar default is written.</p>}{defaultNeedsValue && <div className="field-pair"><label className="field"><span>Verified default value</span><input value={defaultValue} onChange={(event) => { setDefaultValue(event.target.value); setMappingPreview(null); }} placeholder="true, false, integer, or text" /></label><label className="field"><span>Default applies to OS versions</span><input value={defaultOsVersion} onChange={(event) => { setDefaultOsVersion(event.target.value); setMappingPreview(null); }} placeholder=">=12.0" /></label></div>}{matchedValueRequired ? <label className="field"><span>Matched value — required for a true/false field</span><select value={matchedValue} onChange={(event) => { setMatchedValue(event.target.value); setMappingPreview(null); }}><option value="">Choose true or false</option><option value="true">true</option><option value="false">false</option></select></label> : <label className="field"><span>Matched value (optional, for bare or multi-value commands)</span><input value={matchedValue} onChange={(event) => { setMatchedValue(event.target.value); setMappingPreview(null); }} placeholder="Leave empty when one placeholder supplies the value" /></label>}<label className="field"><span>Reviewer (optional provenance)</span><input value={author} onChange={(event) => { setAuthor(event.target.value); setMappingPreview(null); setIgnorePreview(null); }} placeholder="Operator name or handle" /></label></fieldset>}
    {mappingPreview && <WritePreview preview={mappingPreview} label="Backend mapping dry-run" />}
    {ignoreOpen && <section className="ignore-panel" aria-label="Not a security setting"><div><span className="block-label">Not a security setting</span><p>This writes a permanent vendor-pack ignore entry. It removes the question but never changes a verdict.</p></div><label className="field"><span>Reason — required</span><textarea value={ignoreReason} onChange={(event) => { setIgnoreReason(event.target.value); setIgnorePreview(null); }} placeholder="Explain why this line carries no security setting" /></label>{ignorePreview && <WritePreview preview={ignorePreview} label="Backend ignore dry-run" />}<div className="review-actions"><button className="button secondary" disabled={ignoreReason.trim().length < 2 || saving !== null} onClick={requestIgnorePreview}><Sparkles size={16} />{saving === 'ignore-preview' ? 'Generating…' : ignorePreview ? 'Refresh ignore preview' : 'Preview ignore entry'}</button><button className="button" disabled={!ignorePreview || saving !== null} onClick={confirmIgnore}><Ban size={16} />{saving === 'ignore-confirm' ? 'Confirming…' : 'Confirm not a security setting'}</button></div></section>}
    {error && <p className="inline-error" role="alert">{error}</p>}<div className="review-actions"><button className="button secondary" disabled={mappingIncomplete || saving !== null} onClick={requestPreview}><Sparkles size={16} />{saving === 'mapping-preview' ? 'Generating…' : mappingPreview ? 'Refresh preview' : 'Preview exact write'}</button><button className="button" disabled={!mappingPreview || saving !== null} onClick={confirm}><CheckCircle2 size={16} />{saving === 'mapping-confirm' ? 'Confirming…' : 'Confirm mapping'}</button><button className="button secondary" aria-expanded={ignoreOpen} onClick={() => { setIgnoreOpen((open) => !open); setError(null); }}><Ban size={16} />Not a security setting</button></div></div>;
}

function WritePreview({ preview, label }: { preview: ConfirmResult; label: string }) {
  return <div className="write-preview"><span className="block-label">{label} · {preview.pack_version}</span><pre>{preview.fragment_yaml}</pre><small>Target: {preview.pack_path} · Nothing has been written yet.</small></div>;
}

function parseValue(value: string): string | number | boolean {
  if (value === 'true') return true;
  if (value === 'false') return false;
  if (/^-?\d+(?:\.\d+)?$/.test(value)) return Number(value);
  return value;
}
