import { ArrowDownUp, CheckCircle2, ChevronRight, Sparkles } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { confirmCluster, getClusters, getSuggestions, type Cluster, type ConfirmRequest, type SuggestionList } from '../../api/client';
import { EmptyState, ErrorState, LoadingState } from '../../components/StateViews';
import { useAsync } from '../../hooks/useAsync';

export function TrainingPage({ scanId }: { scanId: string }) {
  const state = useAsync(() => getClusters(scanId), [scanId]);
  const clusters = useMemo(() => [...(state.data ?? [])].sort((a, b) => b.device_count - a.device_count), [state.data]);
  const [selected, setSelected] = useState<Cluster | null>(null);
  useEffect(() => { if (!selected && clusters.length) setSelected(clusters[0]); }, [clusters, selected]);
  if (state.loading) return <section className="page"><LoadingState label="Loading unmatched command clusters" /></section>;
  if (state.error) return <section className="page"><ErrorState message={state.error} retry={state.reload} /></section>;
  if (!clusters.length) return <section className="page"><header className="page-header"><div><span className="eyebrow">Mapping trainer</span><h1>Human-reviewed learning queue</h1></div></header><EmptyState title="Nothing needs labelling" detail="Every observed line matched a known vendor-pack mapping." /></section>;
  return <section className="page"><header className="page-header"><div><span className="eyebrow">Mapping trainer</span><h1>Resolve unknown commands</h1><p>Suggestions only pre-fill the review. A human confirmation is always required before a mapping is written.</p></div><div className="security-pill"><ArrowDownUp size={15} />Largest impact first</div></header>
    <div className="training-layout"><aside className="cluster-list panel"><div className="panel-heading"><div><span className="panel-label">Open clusters</span><h2>{clusters.length} questions</h2></div></div>{clusters.map((cluster) => <button key={cluster.cluster_id} className={`cluster-row ${selected?.cluster_id === cluster.cluster_id ? 'active' : ''}`} onClick={() => setSelected(cluster)}><div><code>{cluster.template}</code><small>{cluster.vendor}{cluster.scope ? ` · ${cluster.scope}` : ''}</small></div><span className="impact-count"><strong>{cluster.device_count}</strong> devices</span><ChevronRight size={15} /></button>)}</aside>{selected && <ClusterReview key={selected.cluster_id} cluster={selected} onConfirmed={() => { setSelected(null); state.reload(); }} />}</div>
  </section>;
}

function ClusterReview({ cluster, onConfirmed }: { cluster: Cluster; onConfirmed: () => void }) {
  const state = useAsync(() => getSuggestions(cluster.cluster_id), [cluster.cluster_id]);
  const [field, setField] = useState(''); const [absent, setAbsent] = useState<'unknown' | 'default'>('unknown'); const [defaultValue, setDefaultValue] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [showPreview, setShowPreview] = useState(false);
  useEffect(() => { setField(state.data?.suggestions[0]?.canonical_field ?? ''); setAbsent('unknown'); setDefaultValue(''); setShowPreview(false); }, [state.data]);
  if (state.loading) return <div className="review-pane"><LoadingState label="Ranking canonical fields" /></div>;
  if (state.error) return <div className="review-pane"><ErrorState message={state.error} retry={state.reload} /></div>;
  const suggestions = state.data as SuggestionList | null;
  async function confirm() { if (!field) { setError('Choose a canonical field or leave this cluster unresolved.'); return; } const payload: ConfirmRequest = { canonical_field: field, absent, default: absent === 'default' ? parseDefault(defaultValue) : null }; setSaving(true); setError(null); try { await confirmCluster(cluster.cluster_id, payload); onConfirmed(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Confirmation failed.'); } finally { setSaving(false); } }
  return <div className="review-pane panel"><div className="review-header"><span className="panel-label">Command template</span><code>{cluster.template}</code><div className="impact-summary"><strong>{cluster.device_count}</strong> devices · <strong>{cluster.line_count}</strong> lines covered by this answer</div></div><fieldset><legend>Choose one canonical field</legend><div className="suggestion-list">{suggestions?.suggestions.map((item) => <label key={item.canonical_field} className={`suggestion ${field === item.canonical_field ? 'selected' : ''}`}><input type="radio" name="field" value={item.canonical_field} checked={field === item.canonical_field} onChange={() => setField(item.canonical_field)} /><span className="score">{Math.round(item.score * 100)}</span><div><code>{item.canonical_field}</code><p>{item.description}</p><small>{item.tier} suggestion</small></div></label>)}<label className={`suggestion none ${field === '' ? 'selected' : ''}`}><input type="radio" name="field" checked={field === ''} onChange={() => setField('')} /><span className="score">—</span><div><strong>None of these</strong><p>Leave this cluster unresolved. It will continue to produce NOT DETERMINED.</p></div></label></div></fieldset>
    {field && <fieldset><legend>When this command is absent</legend><div className="radio-row"><label><input type="radio" checked={absent === 'unknown'} onChange={() => setAbsent('unknown')} />Unknown — do not infer a device default</label><label><input type="radio" checked={absent === 'default'} onChange={() => setAbsent('default')} />Use a verified device default</label></div>{absent === 'default' && <label className="field"><span>Default value</span><input value={defaultValue} onChange={(event) => setDefaultValue(event.target.value)} placeholder="true, false, integer, or text" /></label>}</fieldset>}
    {showPreview && field && <div className="write-preview"><span className="block-label">Mapping preview</span><pre>{`cluster: ${cluster.signature}\ncanonical: ${field}\nabsent: ${absent}${absent === 'default' ? `\ndefault: ${defaultValue}` : ''}`}</pre></div>}{error && <p className="inline-error" role="alert">{error}</p>}<div className="review-actions"><button className="button secondary" disabled={!field} onClick={() => setShowPreview((value) => !value)}><Sparkles size={16} />{showPreview ? 'Hide preview' : 'Preview write'}</button><button className="button" disabled={!field || saving || (absent === 'default' && defaultValue === '')} onClick={confirm}><CheckCircle2 size={16} />{saving ? 'Confirming…' : 'Confirm mapping'}</button></div></div>;
}
function parseDefault(value: string): string | number | boolean { if (value === 'true') return true; if (value === 'false') return false; if (/^-?\d+$/.test(value)) return Number(value); return value; }
