/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a batch of configuration files and start a scan */
        post: operations["createScan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example scn_01J9ZK4Q8M3T */
                scan_id: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        /** Scan status, progress and device list */
        get: operations["getScan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example scn_01J9ZK4Q8M3T */
                scan_id: components["parameters"]["ScanId"];
                /** @example dev_01J9ZK4QA7N2 */
                device_id: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        /** Findings for one device, each with cited evidence and remediation */
        get: operations["getDeviceResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/devices/{device_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example scn_01J9ZK4Q8M3T */
                scan_id: components["parameters"]["ScanId"];
                /** @example dev_01J9ZK4QA7N2 */
                device_id: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        /** Per-device PDF report */
        get: operations["getDeviceReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example scn_01J9ZK4Q8M3T */
                scan_id: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        /** Unmatched-line clusters for this scan, sorted by device count descending */
        get: operations["listClusters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clusters/{cluster_id}/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example clu_7f3a9c2e */
                cluster_id: components["parameters"]["ClusterId"];
            };
            cookie?: never;
        };
        /**
         * Ranked candidate canonical fields for a cluster
         * @description Advisory only. Ranks the cluster template against canonical field
         *     descriptions. Nothing here is applied without a human calling confirm.
         */
        get: operations["getClusterSuggestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clusters/{cluster_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example clu_7f3a9c2e */
                cluster_id: components["parameters"]["ClusterId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Human confirms a mapping; writes packs/learned/<vendor>.yaml and reloads */
        post: operations["confirmCluster"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/reevaluate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example scn_01J9ZK4Q8M3T */
                scan_id: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-run mapping and evaluation from the parse cache with current packs */
        post: operations["reevaluateScan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema/fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Canonical fields and their plain-English descriptions */
        get: operations["listSchemaFields"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Installed packs and versions */
        get: operations["listPacks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Framework: "cis" | "nist" | "stig" | "iso";
        /** @enum {string} */
        Verdict: "PASS" | "FAIL" | "NOT_DETERMINED";
        /** @enum {string} */
        Severity: "critical" | "high" | "medium" | "low" | "info";
        /** @enum {string} */
        FieldState: "mapped" | "defaulted" | "unknown";
        Error: {
            code: string;
            message: string;
        };
        ScanCreated: {
            scan_id: string;
        };
        Counts: {
            pass: number;
            fail: number;
            not_determined: number;
        };
        DeviceSummary: {
            device_id: string;
            filename: string;
            hostname: string | null;
            /** @description Vendor pack id that detected this file; null until detected or if none matched. */
            vendor: string | null;
            /** @enum {string} */
            status: "queued" | "running" | "completed" | "failed";
            error: null | components["schemas"]["Error"];
            counts: components["schemas"]["Counts"];
        };
        Scan: {
            scan_id: string;
            framework: components["schemas"]["Framework"];
            /** @enum {string} */
            status: "queued" | "running" | "completed" | "failed";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            finished_at: string | null;
            progress: {
                total: number;
                done: number;
                failed: number;
            };
            devices: components["schemas"]["DeviceSummary"][];
        };
        Identification: {
            hostname: string | null;
            vendor: string | null;
            os_family: string | null;
            os_version: string | null;
            model: string | null;
            serial: string | null;
        };
        Evidence: {
            canonical_field: string;
            /** @description Null when state is defaulted. */
            line: number | null;
            /** @description The cited config line after redaction. Secrets appear as ****; algorithm tokens are kept. */
            text: string | null;
            mapping_id: string;
            pack_version: string;
            state: components["schemas"]["FieldState"];
        };
        Remediation: {
            fix_id: string;
            commands: string[];
            reload_required: boolean;
            rollback: string[];
        };
        Finding: {
            rule_id: string;
            framework: components["schemas"]["Framework"];
            title: string;
            severity: components["schemas"]["Severity"];
            verdict: components["schemas"]["Verdict"];
            /** @description Set only for NOT_DETERMINED. */
            reason: null | {
                /** @enum {string} */
                code: "required_field_unknown" | "collection_unknown" | "not_applicable";
                fields: string[];
            };
            evidence: components["schemas"]["Evidence"][];
            /** @description Set only for FAIL. */
            remediation: null | components["schemas"]["Remediation"];
        };
        DeviceResult: {
            scan_id: string;
            device_id: string;
            filename: string;
            config_sha256: string | null;
            identification: components["schemas"]["Identification"];
            pack_versions: string[];
            coverage: {
                lines_total: number;
                lines_mapped: number;
                lines_unmapped: number;
            };
            findings: components["schemas"]["Finding"][];
        };
        Cluster: {
            cluster_id: string;
            vendor: string;
            /** @description Hash of the normalised template. */
            signature: string;
            /** @description Normalised line with typed placeholders (<IP>, <MAC>, <HOST>, <IFACE>, <STR>, <INT>). */
            template: string;
            /** @description Normalised enclosing block, if any. */
            scope: string | null;
            device_count: number;
            line_count: number;
            /** @enum {string} */
            status: "open" | "confirmed";
        };
        Suggestion: {
            canonical_field: string;
            description: string;
            score: number;
            /** @enum {string} */
            tier: "lexical" | "embedding" | "llm";
        };
        SuggestionList: {
            cluster_id: string;
            template: string;
            suggestions: components["schemas"]["Suggestion"][];
        };
        ConfirmRequest: {
            canonical_field: string;
            /** @enum {string} */
            absent: "unknown" | "default";
            /** @description Required non-null when absent is default; must be null when absent is unknown. */
            default: boolean | number | string | null;
        };
        ConfirmResult: {
            mapping_id: string;
            canonical_field: string;
            pack: string;
            pack_version: string;
            path: string;
            cluster_signature: string;
        };
        SchemaField: {
            path: string;
            /** @enum {string} */
            type: "boolean" | "integer" | "string";
            /** @description True if the path passes through a list ([]). */
            collection: boolean;
            description: string;
        };
        Pack: {
            id: string;
            /** @enum {string} */
            kind: "vendor" | "rules" | "fixes" | "learned";
            version: string;
            /** @enum {string} */
            source: "base" | "learned";
            path: string;
            valid: boolean;
            /** @description Validation error naming the offending field when valid is false. */
            error: string | null;
        };
    };
    responses: {
        /** @description Malformed request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "no_files",
                 *       "message": "At least one configuration file is required."
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "not_found",
                 *       "message": "Scan scn_01J9ZK4Q8M3T was not found."
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Upload exceeds the configured size limit. */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "payload_too_large",
                 *       "message": "Upload exceeds the size limit."
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Request is well-formed but semantically invalid. */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "unknown_canonical_field",
                 *       "message": "services.ssh.timeot is not a canonical field."
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @example scn_01J9ZK4Q8M3T */
        ScanId: string;
        /** @example dev_01J9ZK4QA7N2 */
        DeviceId: string;
        /** @example clu_7f3a9c2e */
        ClusterId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createScan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** @description One configuration file per device. Raw text is redacted at ingest and never logged. */
                    files: string[];
                    framework: components["schemas"]["Framework"];
                };
            };
        };
        responses: {
            /** @description Scan accepted; device jobs queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "scan_id": "scn_01J9ZK4Q8M3T"
                     *     }
                     */
                    "application/json": components["schemas"]["ScanCreated"];
                };
            };
            400: components["responses"]["BadRequest"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["Unprocessable"];
        };
    };
    getScan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example scn_01J9ZK4Q8M3T */
                scan_id: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current scan state. Poll until status is completed or failed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scan"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getDeviceResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example scn_01J9ZK4Q8M3T */
                scan_id: components["parameters"]["ScanId"];
                /** @example dev_01J9ZK4QA7N2 */
                device_id: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-device result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResult"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getDeviceReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example scn_01J9ZK4Q8M3T */
                scan_id: components["parameters"]["ScanId"];
                /** @example dev_01J9ZK4QA7N2 */
                device_id: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PDF with identification, findings by severity, cited lines and remediation. */
            200: {
                headers: {
                    /** @example attachment; filename="cisco_ios_minimal.pdf" */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Device not finished yet, or it failed to parse. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "device_not_ready",
                     *       "message": "Device result is not available yet."
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listClusters: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example scn_01J9ZK4Q8M3T */
                scan_id: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One entry per normalised template signature. Templates contain typed placeholders, never raw identifiers. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cluster"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getClusterSuggestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example clu_7f3a9c2e */
                cluster_id: components["parameters"]["ClusterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Candidates, highest score first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "cluster_id": "clu_7f3a9c2e",
                     *       "template": "ip ssh time-out <INT>",
                     *       "suggestions": [
                     *         {
                     *           "canonical_field": "services.ssh.timeout",
                     *           "description": "How many seconds an SSH client has to finish logging in before the server drops the connection.",
                     *           "score": 0.82,
                     *           "tier": "lexical"
                     *         },
                     *         {
                     *           "canonical_field": "session.idle_timeout",
                     *           "description": "How many seconds an inactive management session stays open before the device logs it out.",
                     *           "score": 0.41,
                     *           "tier": "lexical"
                     *         },
                     *         {
                     *           "canonical_field": "mgmt.vty_lines[].exec_timeout",
                     *           "description": "How many seconds an idle remote login on this line stays open before it is disconnected.",
                     *           "score": 0.37,
                     *           "tier": "lexical"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["SuggestionList"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    confirmCluster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example clu_7f3a9c2e */
                cluster_id: components["parameters"]["ClusterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmRequest"];
            };
        };
        responses: {
            /** @description Learned mapping written and registry reloaded; parse cache invalidated for affected scans. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "mapping_id": "learned.cisco_ios.clu_7f3a9c2e",
                     *       "canonical_field": "services.ssh.timeout",
                     *       "pack": "cisco_ios_learned",
                     *       "pack_version": "cisco_ios_learned@1.0.1",
                     *       "path": "packs/learned/cisco_ios.yaml",
                     *       "cluster_signature": "7f3a9c2e41b0d5a8"
                     *     }
                     */
                    "application/json": components["schemas"]["ConfirmResult"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Ambiguous overlap with an existing mapping, or cluster already confirmed. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "mapping_overlap",
                     *       "message": "Pattern overlaps ios.ssh.version at equal priority."
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["Unprocessable"];
        };
    };
    reevaluateScan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example scn_01J9ZK4Q8M3T */
                scan_id: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Re-evaluation queued. Poll GET /api/scans/{scan_id}. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "scan_id": "scn_01J9ZK4Q8M3T"
                     *     }
                     */
                    "application/json": components["schemas"]["ScanCreated"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Scan is still running. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "scan_running",
                     *       "message": "Wait for the current run to finish."
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listSchemaFields: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flattened from schemas/canonical.schema.json. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "path": "services.ssh.version",
                     *         "type": "integer",
                     *         "collection": false,
                     *         "description": "Which SSH protocol version the server allows; version 1 is broken and only version 2 should be accepted."
                     *       },
                     *       {
                     *         "path": "interfaces[].proxy_arp",
                     *         "type": "boolean",
                     *         "collection": true,
                     *         "description": "Whether the port answers address-resolution requests on behalf of other hosts, which can let traffic bypass intended routing."
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["SchemaField"][];
                };
            };
        };
    };
    listPacks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every pack currently loaded by the registry. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": "cisco_ios",
                     *         "kind": "vendor",
                     *         "version": "1.0.0",
                     *         "source": "base",
                     *         "path": "packs/vendors/cisco_ios.yaml",
                     *         "valid": true,
                     *         "error": null
                     *       },
                     *       {
                     *         "id": "cis",
                     *         "kind": "rules",
                     *         "version": "1.0.0",
                     *         "source": "base",
                     *         "path": "packs/rules/cis.yaml",
                     *         "valid": true,
                     *         "error": null
                     *       },
                     *       {
                     *         "id": "cisco_ios",
                     *         "kind": "fixes",
                     *         "version": "1.0.0",
                     *         "source": "base",
                     *         "path": "packs/fixes/cisco_ios.yaml",
                     *         "valid": true,
                     *         "error": null
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["Pack"][];
                };
            };
        };
    };
}
